### ISSUE TITLE
Simulated data

### ISSUE THREAD

**Issue by robertoguarnieri** [agricolab/ARtACS#2]
Is there a way to create a simulated data (eeg+tAcs stimulation)?
Thanks

**Comment by agricolab** [comment]
Sure,  the following snippet should simulate an evoked response overlaid with a strong artifact based on a  sinus with some distortion of the waveform, but no saturation. The artifact amplitude is modulated by an Ornstein–Uhlenbeck process.
```                                 
setup                = generate.generic();
signal = generate.recording(setup);
```
tweak the setup parameters according to your liking. They are explained somewhat in  https://github.com/agricolab/ARtACS/blob/master/src/%2Bgenerate/generic.m  ```generate.random()``` creates a random setup.

**Comment by robertoguarnieri** [comment]
Ok, thank you very much.

I applied the method.
I generated a simulated signal. After that I correlated the filtered_signal with (noise+sum(echt) assuming that the last one is the signal without tACS artifact.

Hoewver the correlation is about 0.5 (not very high). Why/

Thanks

Kind Regards

________________________________
Da: Robert Guggenberger <notifications@github.com>
Inviato: lunedì 15 aprile 2019 16:50
A: agricolab/ARtACS
Cc: roberto9110; Author
Oggetto: Re: [agricolab/ARtACS] Simulated data (#2)


Sure, the following snippet should simulate an evoked response overlaid with a strong artifact based on a sinus with some distortion of the waveform, but no saturation. The artifact amplitude is modulated by an Ornstein–Uhlenbeck process.

setup                = generate.generic();

signal = generate.recording(setup);



tweak the setup parameters according to your liking. They are explained somewhat in https://github.com/agricolab/ARtACS/blob/master/src/%2Bgenerate/generic.m generate.random() creates a random setup.

**Comment by agricolab** [comment]
probably because of residuals of the artifact.

**Comment by agricolab** [comment]
if you take a look at https://github.com/agricolab/ARtACS/blob/master/img/recovery_ecg.png

you can see that you have a terrible recovery of single trials also for real data.
