### ISSUE TITLE
Is there a paper to cite?

### ISSUE THREAD

**Issue by robertoguarnieri** [agricolab/ARtACS#3]
Is there a paper to cite?

**Comment by agricolab** [comment]
Thanks for asking, there is https://github.com/agricolab/ArtACS_preprint/blob/master/docs/main.pdf, and you can cite the repo itself at Robert Guggenberger (2017). ARtACS @ http://doi.org/10.5281/zenodo.581408

**Comment by agricolab** [comment]
I should

**Comment by agricolab** [comment]
you might also be interested in the work of Alex Casson and Siddharth Kohli, e.g. https://www.mdpi.com/1424-8220/19/1/190.
