### ISSUE TITLE
Noise Level

### ISSUE THREAD

**Issue by robertoguarnieri** [agricolab/ARtACS#4]
I have a question. The parameter noise level, how much high can it be?

Could be intended between 0 a 1, or more?

And how to set it for a realistic simulation? Thanks

**Comment by agricolab** [comment]
The parameter defines the amplitude  of the brown noise added to the generated signal. Consider that there are no units, and a good value depends on the values for the tacs and the eeg, too. i just set it empirically based on playing around. in the end it boils down what signal is of interest to you and how strong you believe the signal to be in absence of stimulation. you could e.g. measure the snr for your signal of interest by doing a recording. 

anyways, nothing will beat a measurement with the devices you will actually use. i decided to use a recording of the ecg at the arm, as i could be quite certain that tacs at the arm would not affect the shape of the ecg.
